# Generated by Django 2.0.1 on 2018-01-04 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_aboutme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutme',
            name='email',
        ),
        migrations.RemoveField(
            model_name='aboutme',
            name='time',
        ),
        migrations.RemoveField(
            model_name='aboutme',
            name='time2',
        ),
    ]
