# Generated by Django 2.0.1 on 2018-01-05 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20180104_2001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mainImage', models.ImageField(upload_to='home/servicos', verbose_name='Imagem Principal')),
                ('service', models.CharField(max_length=300, verbose_name='Seviço')),
                ('slug', models.SlugField(verbose_name='Atalho')),
                ('description', models.CharField(max_length=1000, verbose_name='Descrição do serviço')),
                ('modalImage1', models.ImageField(upload_to='home/servicos', verbose_name='Imagem de exemplo 1')),
                ('modalImage2', models.ImageField(upload_to='home/servicos', verbose_name='Imagem de exemplo 2')),
                ('modalImage3', models.ImageField(upload_to='home/servicos', verbose_name='Imagem de exemplo 3')),
            ],
            options={
                'ordering': ['service'],
                'verbose_name_plural': 'Serviços',
                'verbose_name': 'Serviço',
            },
        ),
    ]
