# Generated by Django 2.0.1 on 2018-01-05 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='slug',
        ),
    ]
