# Generated by Django 2.0.1 on 2018-01-05 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_service_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.SlugField(default='kçqkd', editable=False, unique=True, verbose_name='Atalho'),
            preserve_default=False,
        ),
    ]
